services:
  ner:
    container_name: ner_service
    image: ner_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - $APP_PORT:$APP_PORT
    env_file:
      - .env
    links:
      - db

  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - $DB_PORT:$DB_PORT
    env_file:
      - .env

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: celery
    command: --app=src.worker.celery worker --loglevel=info
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
